# Generated by Django 4.1.3 on 2022-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
