# Generated by Django 4.1.3 on 2023-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
