# Generated by Django 4.1.3 on 2023-01-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_recipe_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_title',
        ),
    ]
